#define NUMBER_OF_CALLS 393

struct call_definition {
    const char *call;
    const char *def;
} call_list[] = {
        {"(Cross) Trade Your Neighbor [Direction]","From waves: trailers follow (cross) your neighbor, while leads step ahead, quarter [direction, default right], & circulate."},
        {"(Grand) (Left) 1/4 | 3/4 Cross","This is 2/3 of a (grand) (left) <N/4> Mix. Arm Turn the indicated fraction, and the centers Cross Run. \"1/4 cross\" is a right-hand call."},
        {"(Left | Twin) Orbit Circulate","Leader on the right crossover zoom, others trade circulate. For \"left orbit circulate\", leader on the left crossover zoom.  For \"twin orbit circulate\" both leaders crossover zoom."},
        {"(Reverse) Swap the Windmill","1/2 (reverse) swap around.  Form twin stars w/ wave down the middle.  Spin the windmill ends as you are."},
        {"[Any Flowing Call] Plus 1 | 2","After any call that has a natural veering or sweeping direction, everyone slides laterally in that direction that number of half matrix spots. Plus 2 has people sliding one position."},
        {"[Anyone] Advance to a Column","[anyone] walk others dodge; col circ, centers trade, col circ"},
        {"[Anyone] Break the Alamo","From alamo ring/O spots, or t-boned 2x4 with [anyone] in center. [anyone] in your box follow thru; others leaders loop 1 around trailer. As couples extend to make 2-faced lines."},
        {"[Anyone] Bring Us Together","[anyone] move into the center, circle left 1/2, slide out to the left. others single rotate 1/4 and phantom follow thru"},
        {"[Anyone] Bypass","Pass thru; [anyone] *stand still* while others u-turn back. eg, \"1/2 tap the [other people]\"."},
        {"[Anyone] Cross Run the Top","[anyone] cross run, fan the top."},
        {"[Anyone] Cross Swivel","[anyone] cross fold. facing dancers single circle to a wave in flow direction."},
        {"[Anyone] Curve [Direction]","Like [anyone] press [direction] but w/ a 1/4 turn in the natural direction. space invader.  \"Curve in\" and \"curve out\" are relative to the entire formation."},
        {"[Anyone] Finish the Stack","This is the final “some people cross over and take right hands” part of Stack the Line. (Others may need to dodge.)"},
        {"[Anyone] Mark Time","[anyone] (#1 and #2) run,col circ,trade,roll while others partner tag,wheel and deal (ending up on outside)"},
        {"[Anyone] Pinwheel","Typically from a promenade: designated couple Cast Off 3/4 to finish as outsides of a starting DPT. The others Wheel and Deal to become the centers. From tidal line, designated cast 3/4 and end as outsides, others wheel and deal to end as centers."},
        {"[Anyone] Rolling Ripple [M] X [N]","From a line. Designated dancer Ripple [m]; new dancer occupying designated dancer's original starting position. Ripple the next given number; repeat part 2 for each additional given number."},
        {"[Anyone] Run the Top","[anyone] run, IF FACING COUPLES, THEN STEP TO A WAVE, fan the top."},
        {"[Anyone] Run the Wheel","[anyone] run & curve right/left, while others do their part of trade and roll."},
        {"[Anyone] Shove Off","Designated dancer run away from partner, nondesignated slide into vacated spot w/o turning (do your part of a run)"},
        {"[Anyone] Single Mark Time","[anyone] run, 1/2 box circ, trade, roll; while others partner tag, single wheel (ending up on outside)"},
        {"[Anyone] Swivel","From couple. [anyone] fold. both single circle to a wave in flow direction."},
        {"[Anyone] Tie","Often from completed DPT. note designees. peel off. designated couples circ & bend the line; others bend the line & couples circ."},
        {"[Anyone] Tip Toe","The designated people Press ahead, dragging their partner (often backwards) with them."},
        {"[Anything] 'Em Up","[anything]; hinge. centers hinge the lock while ends counter rotate & roll"},
        {"[Anything] By [By [By]]","For [anything] then ends with a courtesy turn.  Do 1/4 more (\"as couples roll\") then slither [and slide [and slither]]."},
        {"[Anything] Cover Up","[anything]; 1/2 circ; centers recycle while ends natural pass in"},
        {"[Anything] the Wave","From waves.  Extend twice to DPT, then do [anything]."},
        {"[Atc] & Spin [Call]","Tag to the 3/4 position.  Centers cast off 3/4, while the ends do their part of [call] (ie, \"Flip and Spin Rally\")."},
        {"[Atc] & Spin [Direction]","Tag to the 3/4 position. Centers cast off 3/4, while the ends quarter [direction]. If no direction is given, the ends do not turn."},
        {"[Atc] and Dodge","[atc] back, but scoot and dodge instead of scoot back."},
        {"[Atc] and Trade","Tag to the 3/4 position. Centers Trade the Wave while the ends trade."},
        {"[Atc] Eroo","[atc] to a diamond, ctrs cast 3/4, ends circulate"},
        {"[Atc] the Yellow Brick Road","[atc] to half tag; follow the yellow brick road"},
        {"[Atc] the Yellow Bricking [Anything]","[atc] to half tag; follow the yellow bricking [anything]"},
        {"[Atc] to a Diamond","[atc] to 3/4 tag, ends quarter to direction of center wave"},
        {"[Atc] to an Hourglass","[atc] to a diamond, very centers snake"},
        {"[Atc] to an Interlocked Diamond","[atc] to a diamond, very centers slither"},
        {"[Atc]-Eroo","[atc] to 3/4 tag.  if not already diamonds, ends 1/4 to handhold (typ right). ends circulate while centers cast 3/4."},
        {"[Atc]Ers Dream (Nightmare)","[atc] to 3/4 tag. ends qtr right (left) & circ, while centers swing, slip, slide thru (step thru, finish slide thru). ends in parallel lines."},
        {"[Atc]Ers Flow","[atc] to half tag; tandem trade; slip"},
        {"[Atc]Ers Flow but Criss Cross It","[atc] to half tag; tandem trade the wave; slip"},
        {"[Atc]Ers Flow but Cross It","[atc] to half tag; tandem cross roll; slip"},
        {"[Call] and Anything","For calls that finish with the centers casting 3/4: instead have centers cast 1/4 and ends u-turn back. \"Spin Chain and Anything\" means \"spin chain thru and anything\"."},
        {"[Cross] Clover the Horn","Trailers 1/2 stable, [cross] cloverleaf. everyone pass thru."},
        {"[Grand] Single [Cross] Concentric Concept","Single Concentric = 4 person call which takes a 2-person call as argument.  [Grand] means work in whole formation, very center 2, then next two, etc."},
        {"[N/4] Chain & Circulate In","Center cast [n/4], center 2 trade, cast 3/4 (always) and spread.  ends circulate & cross over circulate.  fan chain and circulate in == 3/4 chain and circulate in.  change lanes == 1/4 chain and circulate in."},
        {"<Atc>Ers Flow but Criss Cross It","<atc> to 1/2 tag, tandem trade the wave, slip"},
        {"1/2 & 1/2 Concept","Do the first half of the first call, and then the second half of the second call."},
        {"3x1 Concept","NxM = N leads/belles, M trailers/beaus. \"1\" think single, do call 3x3 & compress. (There is cheese.)"},
        {"3x3","Centers and ends do call normally; third dancer fits between them"},
        {"4 Phantom Interlocked Blocks Formation","Done in a 4x4 matrix: Each person deduces which “Block” (C1 blocks) formation they are in, and does the call in that block, however many people it may contain."},
        {"About","Explode."},
        {"Alter the Diamond","Counter rotate the diamond 1/2, flip the diamond, fan back (3 parts)"},
        {"An Anchor","Very ends counter rotate while center 6 trade; end of wave of 6 counter rotate while center 4 trade; center 2 trade while ends pass in (6-4-2)"},
        {"An Anchor but [Anything]","Anchor but replace the final swing&slip with [anything]"},
        {"Anchor [Anyone] For a [Call]","The call is done in such a way that the designated people stay on the same spot on the floor, and the other people in her setup compensate for that by adjusting their ending setup so that it has the correct shape. The designated person can still change facing direction. \"[anyone] is a barstool.\""},
        {"Bail Out","Centers short & sweet then counter rotate, while ends 1/2 circ then hinge."},
        {"Bail Out but [Anything]","Centers short & sweet then [anything], while ends 1/2 circ then hinge"},
        {"Barge the Action","Square thru 2 the action (do 1st part of barge thru; the action)"},
        {"Barge Thru","Square thru 2, trade by"},
        {"Barrel of Fun","From lines w/ ends facing out: ends bend & touch 1/2, while ctrs 1/4 in and swing thru. All fan the top."},
        {"Beep Beep","Hinge & you all (you all is centers hinge while ends u-turn back)"},
        {"Bits and Pieces","Centers: peel and trail, ah so.  ends: o circ twice, trade. (2 parts; peel and trail: touch & lockit twice, or u turn back & touch)"},
        {"Bridge the Gap","Beaus press left, belles press ahead and left loop 0 (alternatively: tandem twosome fan thru)"},
        {"Buckle and [Anything]","End looking out cross fold; end looking in circulate and fold; others [anything]"},
        {"Cast a Net","Usually from waves or 2-faced lines. 1/2 circ. in center line: very centers cast 3/4 & spread 1 spot, while ends ctr rotate to become very ends. in outer pairs: trade and the inner one spread 1 spot. ends in tidal line."},
        {"Cast an Anchor","Cast off 3/4; an anchor"},
        {"Centers Cut Out","From lines. centers crossover circulate while ends flip in."},
        {"Change the Web","From a 1/4 tag: the center wave does a Swing and the very centers Cast 3/4 while the ends of the wave move forward. The outsides adjust to make two stars, in the same way stars are formed on Explode the Top. The stars turn 5/4 (yes, 5/4.) Then the people who find themselves in the very center Cast 3/4 with each other, while the people behind them in the stars move forward to become ends of the center wave. The others adjust to become outsides of a 1/4 tag."},
        {"Change-O","From columns: #1 and #2 circ, #3 and #4 cross over circ. (ie, those *finishing* in the middle, cross over)"},
        {"Chase Back","Chase the 1/2 tag; scoot back"},
        {"Cheerio","From general columns. Centers partner tag (w/ each other), press ahead, face in. Ends: leaders (if any or both) run, press ahead. If neither end is a lead, they just press ahead (don't sashay)."},
        {"Chip Off","From lines.  outfacing couple (or right couple if both outfacing) link up. other center shove off inward, taking adjacent end."},
        {"Circle the Tag","Circle to a wave. you are now at 1/2 tag."},
        {"Circle to a Two-Faced Line","As couples Single Circle to a Wave. That is, Circle 1/2, then Veer Left."},
        {"Clean Sweep [N/4]","From facing couples. Sweep [n/4] clockwise, veer left, tag the line, leads roll right to a wave.  Ends in box.  4 parts. Reverse means \"mirror\"."},
        {"Clear Out","Circulate, centers couple up while ends like a couple up"},
        {"Clear the Centers but Cross It for [Anything]","Center 4 start a linear cycle then tandem CROSS run outward (usually around further ends). Ends move in an do [anything]. Usually from 1/4 tag, but can also be done from tidal wave, etc."},
        {"Clear the Centers for [Anything]","Center 4 start a linear cycle then tandem run outward (usually around nearest ends). Ends move in an do [anything].  Usually from 1/4 tag, but can also be done from tidal wave, etc."},
        {"Clover Flow","From trade by. ends cloverleaf & pass thru, while centers pass thru & cloverleaf.  ends in tradeby."},
        {"Clover the Wave","From waves.  extend twice to DPT. cloverleaf."},
        {"Cloverleaf Turn","Cloverflow but replace pass thru w/ turn thru.  That is: from a trade by, ends cloverleaf and then turn thru, while the centers turn thru and then cloverleaf.  Ends in 8-chain."},
        {"Cloverleaf Turn Reaction/Reactivate/Etc","Replace the final turn thru of cloverleaf turn w/ turn thru to a wave; that leaves you in a 1/4 tag.  Then reaction/reactivate/etc. (cloverleaf turn is twice (clover and turn thru).)"},
        {"Collapse the [Formation]","Ends detour, centers step and fold"},
        {"Collapse the Interlocked [Formation]","Ends detour, centers step and cross fold"},
        {"Common Spot","R/h miniwaves act as if they are in single location. common point/end/etc if ambiguous."},
        {"Concentric Triple Boxes","321123 dance together."},
        {"Connect the Diamond","Centers hinge and extend; ends cross fold (or fold) to empty spot.  (From normal diamonds: drop in, counter rotate)"},
        {"Continue to Cross Invert","Continues to cross invert the column for N/4."},
        {"Continue to Invert the Column","Continues invert the column 1 more quarter from wherever it is."},
        {"Contour the Line","Hinge, split circulate, split circulate, hinge"},
        {"Convert the Triangle","From tandem-base triangle, apex and trailing point extend to each other, lead point 1/2 run to become point of new wave-based triangle.  From wave- or couple-based triangle, apex steps ahead; any base facing the apex steps behind base to form a tandem; outfacing base (if any) 1/2 run to become new apex."},
        {"Cooperate","From columns. Circulate. 1/2 Circulate. Columns of 6 Invert the Column 2/3. Center diamond drop in. Ends in: waves. (Cheat: tandom reach out.)"},
        {"Cooperate But [Anything]","From columns. Circulate. 1/2 Circulate. Columns of 6 Invert the Column 2/3. Center diamond [anything]."},
        {"Coordinate to a Diamond","Coordinate, but those who trade to become centers of lines at end do an extra hinge. (Possibly a partner hinge.) (This is a \"centers do more\" diamond call.)"},
        {"Counteract","Ends trade & split counter rotate while centers counter rotate then \"anchor new trailing center for trade\" (ie, cross run while hanging on to trailing center, who ends up doing u turn back)"},
        {"Counterpoint","Centers recycle while ends counter rotate"},
        {"Countershake","Ends: 1/4 right, counter rotate, twosome drop in; while centers: shakedown, veer left, as couples extend.  (3 parts) cheat: Concentric Shakedown and solid box of 4 Touch"},
        {"Couples N/4 Twosome","Do as couples until you've turned N/4, then finish the call twosome"},
        {"Cover Up","Circulate 1-1/2; centers recycle while ends natural pass in"},
        {"Cover Up but [Anything]","Cover up but replace the centers' recycle with [anything]"},
        {"Crackle","Typ from trade by: centers touch & lockit, while ends hinge"},
        {"Create a Column","From any distorted column in a 4x4 matrix: If you are in the center phantom columns, do two normal Column Circulates. Otherwise, do two Butterfly or “O” Circulates, as appropriate. (ie, do two column circulates while cheating into the center.)"},
        {"Create a Diamond","Slant touch and 1/2 tag"},
        {"Criss Cross Shadow the Column","1 & 3 1/2 zoom TO OPPOSITE HANDS, cast off 3/4, spread; 2 cloverleaf. 4 circ 1 1/2 TO OPPOSITE HANDS, hinge, extend. (like split phantom columns walk and dodge, collapse phantoms, criss cross the shadow)"},
        {"Criss Cross Shadow to a Diamond","From parallel waves. Ends CRISS CROSS the shadow, lead center peel, trailing center CROSS EXTEND and trade. Ends in twin interlocked diamonds."},
        {"Criss Cross the Diamond","Criss Cross the Deucey; Centers Hinge; Diamond Circulate; and Centers Hinge.  (like 'trade the diamond' except for 1st part.  cheat: weave, trade the diamond.)"},
        {"Criss Cross Your Pleasure","Cross Double Your Pleasure, but replace all extends with cross extends."},
        {"Cross [Anyone] Tie","Often from completed DPT. Note designees. All trail off. designated couples circ & bend the line; others bend the line & couples circ."},
        {"Cross & Divide","From any line of 4: centers 1/2 of a cross run, while ends quarter out to form a couple w/ the centers."},
        {"Cross Breed Thru","Slide Thru, and any trailers Pass Thru, passing left shoulders.  From normal couple facing sashayed couple, results in couples back to back."},
        {"Cross Counterpoint","Centers cross cycle while ends counter rotate"},
        {"Cross Cy Kick","Centers 2/3 cross cycle while ends beaus kick off"},
        {"Cross Double Down","Trailing end (or #4) and adjacent person split circulate twice; others all-8 crossover circulate"},
        {"Cross Double Your Pleasure","From columns: #1 trail&circ to (become lead end) while others extend&trade. #1 of center six trail (to become trailing end) while others extend&trade. ends in parallel 2-faced lines."},
        {"Cross Follow Thru","Follow thru w/ extends replaced w/ cross extends.  From box, weave.  From 1/4 tag, cross extend & hinge."},
        {"Cross Horseshoe Turn","From a 2 x 4 with the Ends in Columns facing Out. Outsides Cross Cloverleaf; centers Quarter In and Cross Trail Thru. (That is, both ends and centers cross.) 2 parts for centers. (Centers can face out; this is not \"cross clover and...\")"},
        {"Cross Linear Cycle","Initially once-removed linear cycle. (starts w/ once removed hinge)"},
        {"Cross Lock 'Em Up","Cross lockit. hinge. centers hinge the lock while ends counter rotate & roll."},
        {"Cross Make a Pass","Those facing diagonal pass thru; centers cast 3/4 (or [anything]) while ends trade and roll"},
        {"Cross Mini Pleasure","From columns. #1 TRAIL, other 6 extend & trade. Center 2 spread, THOSE WHO TRAILED press in. Ends like a couple up. Ends in 1/4 two-faced line. (Starts like double your pleasure.)"},
        {"Cross Pair the Line","Centers trade while ends cross fold. (semi space invader: spot formerly occupied by folder is breathed away.) eg from parallel ocean waves."},
        {"Cross Reactivate to a Diamond","Cross reactivate, but those who trade to become centers of lines at end do an extra hinge. (Possibly a partner hinge.) (This is a \"centers do more\" diamond call.)"},
        {"Cross Replace the Column","Cross invert the column 3/4; #1 and #2 counter rotate while #3 moves up to 2/3 cross cycle with very centers"},
        {"Cross Run Away","From line. centers cross run and roll, while ends face center & right touch 1/2. ends in single 1/4 tag."},
        {"Cross Sashay","Slithery crossfire.  From wave.  Centers slither and step ahead, while ends cross fold."},
        {"Cross Shadow to a Diamond","From parallel waves. Ends cast a shadow, lead center peel, trailing center CROSS EXTEND and trade. Ends in twin interlocked facing diamonds."},
        {"Cross Straight Away","Straight away, but outside jay walks instead of press ahead.  (from 1/4 tag/line, ends of center line extends and release recycle with nearest outside, very center flips out, other outside jay walks)"},
        {"Cross the Ocean","Vertical 1/2 Tag and Weave. (From couples facing it is roughly \"half sashay pass the ocean\")."},
        {"Cross the Top","Spin the top and spread."},
        {"Cross to a Diamond","Usually from lines. Centers cross over circulate while ends slide together and hinge. Can be done from p2p diamonds."},
        {"Cross to an Hourglass","Cross to a diamond (centers cross over circ, ends slide together and hinge), very centers snake."},
        {"Cross to an Interlocked Diamond | Hourglass","Cross to a Diamond (centers cross over circ while ends slide together and hinge), then very centers slither (to an interlocked diamond) or snake (to an hourglass)."},
        {"Cross Town Roll","Trade behind the back; extend."},
        {"Curl Apart","[from 1x4] curl thru (centers trade, ends cross fold, resulting in Z). then centers flip away and original ends press ahead.  cheat: \"slip and switch\" [ends in 1x4]"},
        {"Curl Thru","Crossfire w/o final extend.  [ends in Z]"},
        {"Curli Pass","Curlique, then those facing, wherever they are, Pass Thru.  Often used at the start of the sequence, eg \"heads curli pass\" the final pass thru will be with the sides."},
        {"Curli Wheel","Curlique, then the new trailers walk forward to crossed (left) hands with each other (cross extend), Trade, and step back. While the trailers are doing that, the leads Run right."},
        {"Curlique","Boys touch 1/4 w/ raised hard; girls go 3/4 to the left under the raised hand."},
        {"Cut Across","From 2x4: identify leader/trailer in (split) box of 4.  then, working to concentric box spots, \"leaders\" partner tag & trade while \"trailers\" trade & partner tag. (hint: TRailers start with TRade)"},
        {"Cy Kick","Centers 2/3 recycle while ends beaus kickoff [eg from 3/4 tag, to parallel waves]"},
        {"Derby","Centers trade and spread, while the ends fold then step into the center.  Ends like a cross roll, but note handhold and generous/yoyo/etc for centers."},
        {"Detract [N | Call]","The ends Detour and then Hinge. The centers Box Counter Rotate and then 1/2 Box Circulate. Then those who meet Cast Off [n]/4, or do the [anything] call, while the others “move up”. (This call is similar to “breaker”.)"},
        {"Deuces Wild","From lines. centers trade while ends zoom."},
        {"Diamond Concept (1/4 Thru Family)","For calls that involve sequences of arm turns (Swing Thru, 1/4 Thru, Swing the Fractions, etc.) all arm turns that would involve centers and ends are turned into that many Diamond Circulates, and all arm turns that would take place in the center are done just by the center two people."},
        {"Diamond Concept (Single Wheel Family. 2-Person Shape Changers)","2-person call: The points/centers of each diamond do that call in their disconnected setup. If a shape changer, points become centers and vice versa. In all cases the diamond’s orientation remains the same."},
        {"Diamond Inlet","From parallel waves. Inlet but outeractives do 2/3 recycle instead of recycle. Ends in twin diamonds."},
        {"Diamond Outlet","From diamonds. Outlet but outsides split circ & hinge. (Think of points as ends of 2x4.) Ends in waves."},
        {"Diamond Recycle (From Box)","Facing or \"Split\" recycle. From box.  Facing recycle but those coming into the center hinge (instead of u-turn back)."},
        {"Diamond Recycle (From Diamond)","From diamond. Centers hinge, all wheel and deal. Ends in facing couples. (Ends do normal recycle.) (In 'facing recycle' or 'split recycle' do normally but those coming into the center do centers hinge instead of u-turn back.)"},
        {"Divvy Up","Centers single wheel while ends divide (to face each other). From columns to triple columns (with two waves of three in the center)."},
        {"Dixie Chain","Belles step ahead, right pull by with each other, left pull by with others, who then right pull by with each other."},
        {"Dixie Daisy","Belles step ahead, right pull by with each other, left turn thru, right pull by with each other. (Like dixie chain, but replace left pull by w/ left turn thru.)"},
        {"Dixie Derby","Dixie style to a wave; derby. (Derby is centers trade & spread while ends fold & step into center.)"},
        {"Dixie Spin","Dixie style, fan the top"},
        {"Double Down","Trailing end (or #4) and adjacent person split circulate twice; others all-8 circulate"},
        {"Double the Wave","Fan the top, very center 2 trade (this is 2/3 hot foot spin, just missing a final spin the top)"},
        {"Double Your Pleasure","From columns: #1 peel&circ to (become lead end) while others extend&trade. #1 of center six peel (to become trailing end) while others extend&trade. ends in parallel waves."},
        {"Easy Does It","[usually from lines] concentric zing. remember to move up on the ends (concentric rule)"},
        {"Ends Cut In","Typically from lines. Ends cross over circulate while centers flip out. (From diamonds, results in point-to-point diamonds; centers stay on own side.)"},
        {"Erase","4-person call.  Ends isolate while centers u-turn back toward each other."},
        {"Explode the Clover","Ends cloverleaf while the centers trade and roll. (better name would be \"regroup the clover\"?)."},
        {"Explosion","From columns. #2 & #4 press out. Initially offset two-faced line, slippery couples circulate. (\"slippery\" means very center 2 trade after 1/2 couples circulate.)  Ends in parallel two-faced lines."},
        {"Fall Into a Column","From 1/4 tag. center of wave folds behind end and move ahead to become #1 and #2. ends walk and dodge as needed to get out of the way, becoming #3 and #4"},
        {"Fan & Cross Thru","Touch, slip, cross trail thru"},
        {"Fan Back","Centers cast 3/4 while the ends u-turn back"},
        {"Fan Chain and Circulate In","From waves. Ends circulate & crossover circulate, while centers cast 3/4, very centers trade, cast 3/4, spread."},
        {"Fan Chain the Star","0-3-2-3 quarter the deucey"},
        {"Fan the Gate","[usually from par 2-faced lines] centers cast 3/4, very centers cast 3/4, while ends circ 1 1/2. outer 4 bend the line (and stay together)"},
        {"Fan the Gating [Anything]","[usually from par 2-faced lines] centers cast 3/4, very centers cast 3/4, while ends circ 1 1/2. outer 4 [anything] (and stay together)"},
        {"Fan Thru","Touch, slip, step thru"},
        {"Fiddle Around","Straight Fire like a Couple Up."},
        {"First [Anything]","From waves: leads switch \"with the flow\"; trailers extend and [anything]."},
        {"First Choice","From waves: leads switch with the flow; trailers extend and lock the hinge."},
        {"Flare the Star","From facing couples.1/2 reverse swap around, counter rotate 1/4, reverse flip the diamond, chain down the line.  Zero for belles, exchanges beaus."},
        {"Follow and Criss Cross","Scoot back and cross extend; eroo [2 parts] [eroo = ctrs cast 3/4, ends circ]"},
        {"Follow and Cross","Scoot back [and extend]; eroo [2 parts] [eroo = ctrs cast 3/4, ends circ] [from parallel waves to parallel waves]"},
        {"Follow the Yellow Brick Road","Follow your neighbor, spread, slither; centers follow your neighbor and spread while ends circ 1 1/2; finish fascinate"},
        {"Follow the Yellow Bricking [Anything]","Follow your neighbor, spread, slither; centers follow your neighbor and spread while ends circ 1 1/2; finish fascinating [anything]"},
        {"Fractional Stable","Each person stops turning (but otherwise continues moving) after having turned the given fraction. If you turn one way and then the other, all of those turns add up."},
        {"Go First Class","[normally from waves] leads switch, trailing end circ, trailing centers jay walk. [normally ends in 2-faced lines]. trailers part like scatter circ *but leads switch* (instead of cross roll). can be done from columns; #3 is \"trailing center\" and #4 is \"trailing end\""},
        {"Gravitate","Centers 2/3 linear cycle to become #1 and #2; while ends reverse single rotate & split counter rotate to become #3 and #4. may collide to form clumps."},
        {"Hammerlane","Cross cycle (from facing couples)"},
        {"Hang a Right (Left)","First couple go right (left), next couple go likewise. from completed DPT, tandem as couples right (left) roll to a wave."},
        {"Hang Loose","[from waves] lead center cross run while others peel and trail; peeler trade w/ adjacent (end two); facing pass in; others step forward and bend the line [ends in facing lines]"},
        {"Hinge and Trade","As couples [single hinge and trade]. (Couples hinge, as couples centers trade, all as couples roll.)"},
        {"Hinge the Top","Hinge, fan the top"},
        {"Hit the Wall","Commonly from trade by. centers pass out while ends partner tag."},
        {"Hot Foot Spin","Fan the top, very center 2 trade, spin the top"},
        {"Hourglass Inlet","Diamond Inlet, very centers snake."},
        {"Hourglass Outlet","The center diamond does a Drop In and Hinge, fudging to the appropriate place, while the outsides do a Diamond Outlet.\"Diamond outlet but very centers curve out\""},
        {"I-J-K 1/4 the Alter","Arm turn i/4. centers turn j/4 while ends u-turn back. split counter rotate k/4. flip the diamond."},
        {"I-J-K 1/4 the Alter & Circulate","Arm turn i/4. centers turn j/4 while ends u-turn back. ends circulate while center 2 trade. split counter rotate k/4. flip the diamond."},
        {"I-J-K-L 1/4 the Deucey","Cast i/4, centers cast j/4, end looking out circ while end looking in step into star, center star turns k/4, those who meet turn l/4 while others move up"},
        {"I-J-K-L Relay The Top","Cast i/4. Centers cast j/4 while ends 1/2 circ. Turn the center star k/4 while outsides trade. Those who meet cast l/4 while others hourglass circ."},
        {"In Roll to a Wave","Ends do your part in roll circulate, while centers stably slide over then hinge."},
        {"In/Out/Zoom Roll to a Wave, Here Comes the Wave, Sock It to the Wave","Typically from diamonds: Ends do their part of In/Out/Zoom Roll Circulate/Here Comes the Judge/Sock it to me.  Centers slide over (stably) and hinge. From diamonds to waves.  From waves ends in C1 phantoms."},
        {"Interlocked Boxes","Make four boxes.  work with once-removed box."},
        {"Interlocked Parallelograms","Identifies two parallelogram (non rectangular) 2x2 boxes of real people, each of which does the call."},
        {"Interlocked Phantom 1/4 Tag","Make four single 1/4 tags.  make quarter tag from once removed single quarter tags"},
        {"Invert [Tagger]","Invert the Column 1/2, and you are at the 1/2 tag position."},
        {"Invert Concept","Ends do the centers part and centers do the ends part."},
        {"Isolate","Ends part of lockit (or fan the top)"},
        {"Jam Thru","Pass thru; cross clover and (pass thru, quarter in, pass thru)"},
        {"Kick the Habit","Ends counter rotate while centers leads (of center box) kickoff"},
        {"Lead the Class","From waves. Leads follow your leader (1/2 split circ, tandem cross fold, tandem extend) while trailers (extend, recycle, plus 2, face the center -- aka \"touch of class, face the center\").  Finishes in DPT."},
        {"Lead the Way","Usually from columns. Ends Trade & Roll. Centers Peel Off & Bend the Line. Ends in facing lines."},
        {"Linear Action but Cross It","This is a Linear Action in which the center line does a Slither just prior to the Cast Off 3/4."},
        {"Lines Walk [Dir]","From lines facing: ends pass thru then press ahead *while centers stand stlll*..  All face [dir], then adjust to lines (ends stay ends, centers stay centers)."},
        {"Lock 'Em Up","Lock the hinge (2 parts); centers hinge the lock while ends counter rotate and roll (2 parts)."},
        {"Long Trip","Short trip; center box pass thru while ends (wings) cross fold (ie natural turn and deal)"},
        {"Magic Quick Wrap","#1 and #2 \"magic split counter rotate\", #3 and #4 magic circulate & reset 1/2"},
        {"Make a Pass","Make a pass but cast 3/4"},
        {"Make a Pass but [Anything]","Those facing pass thru; centers [anything] while ends [trade and roll]"},
        {"Melded Concept","From a tidal wave, \"melded as couples trade the wave\".  Go where you would go on \"as couples trade the wave\" and ignore the fact that the person next to you is not facing the same way as you.  Also note there is a distinction between \"melded as couples\" and \"melded phantom as couples\".  The former does not make the setup bigger - you work in your existing 1x8 or 2x4.  Melded phantom as couples or melded phantom tandem requires you to form a 4x4 just like you would for phantom as couples or phantom tandem."},
        {"Mesh","Typ from tandem.  Trailer steps forward to the right side of other. From tandem think \"last half of half sashay\"; from facing dancers think \"left touch\"."},
        {"Mini Pleasure","From columns. #1 peel, other 6 extend & trade. Center 2 spread, peeler press in. Ends like a couple up. Ends in 1/4 tag. (Starts like double your pleasure.)"},
        {"Mix the Line","From facing lines. Retreat the Line and Shuffle the Deck *but you can roll after*.  Ends in completed DPT.  (As couples quarter out, put belle couple in front.)"},
        {"Multiple Setups Working Together","Find the nearest setup (box), work in a 2x4 with that setup"},
        {"Mystic","Centers do the call mirror, ends do it normally."},
        {"Mystic Triple Box","Center triple box does the call mirror, outside triple boxes do the call normally."},
        {"N/4 the Alter","Turn N/4; centers turn N/4 while ends u turn back; turn the star N/4; flip the diamond"},
        {"Nice & Easy","Typically from waves. Centers trade and roll, while ends zing. (Ends in starting DPT.)"},
        {"Nicely","Hinge and cross"},
        {"Nip and Tuck","Belles 3/4 zoom while beaus run and wheel thru.  cheat: couples twosome latch on"},
        {"Once Removed 3x1 Triangle Formation","From 50% offset parallelogram columns, work once-removed w/ dancers in front/behind you."},
        {"Outpost","1/2 (out roll circ or here comes the judge); center 6 trade; center wave ah so while ends o circulate twice"},
        {"Pair the Line","Centers u-turn back while ends fold. (semi space invader: spot formerly occupied by folder is breathed away.) eg from tidal wave."},
        {"Pass the Top","[from facing lines] centers spin the top, explode; while the ends pass thru, ends bend, pass in; everyone slimdown [ends in facing lines]"},
        {"Peel and Trail the Deal","Leads do their part of Peel the Deal (Loop and Tag Zero), while the trailers do their part of Trail the Deal (Cross Loop and Tag Zero)."},
        {"Peel Chain Thru","From trade by or 3/4 tag. centers swing slip as outsides cast back and touch 1/2. fan the top. usually ends in parallel waves."},
        {"Peel the Deal","Loop and Tag Zero."},
        {"Phantom Boxes / Phantom Diamonds","Centers work together, ends work together.  like 'phantom waves' and 'phantom columns'"},
        {"Phantom Offset Waves & Columns Formation","Work in your 100% offset waves (or columns).  Each pair of \"clumps\" in the 4x4 works together."},
        {"Phantom Tandem / Phantom as Couples / Phantom Twosome","Expand formation to 4x4, then form the required tandem/couples with phantoms and do the call"},
        {"Piecewise Concept","Pick out each part, and apply the concept to those parts individually."},
        {"Plus [N]","Slide [N/2] spots in natural veer/sweep dir"},
        {"Polly Wally","Ends: 1/4 To Prom, Step Ahead, Turn another 1/4 same dir, adjust to end in Parallel Lines; Centers: 1/4 To Prom, Step Ahead, 1/4 To Prom, and Step Ahead (to become Leaders in Parallel Lines)."},
        {"Pop","Explode the wave"},
        {"Press for Time","From columns: #3 and #4 Press Out, while #1 and #2 phantom Run and Circulate.  Ends in parallel 2-faced lines. (like tandem twosome trailers stable reach out)"},
        {"Presto","Centers scoot back while ends tandem cross fold; press ahead"},
        {"Push Off","Zip code 1; new ends touch 3/4, new centers fan the top & hinge"},
        {"Push Open the Gate","From 8-chain or inverted lines.  Put centers in if necessary.  All cast 3/4.  Centers pass thru while ends (bend and slide thru)."},
        {"Quick Change","Acey deucey and (centers roll, ends face in)"},
        {"Quick Wrap","#1 & #2 split counter rotate; #3 and #4 circulate & reset 1/2."},
        {"Reactivate to a Diamond","Reactivate, but those who trade to become centers of lines at end do an extra hinge. (Possibly a partner hinge.) (This is a \"centers do more\" diamond call.)"},
        {"Reciprocate","Typically from 3/4 tag or trade by: centers spin the windmill while ends *divide* and touch 3/4."},
        {"Recount","Usually from waves: outeractives 2/3 recycle (to become ends), others anchor the center for cast 1/4 inward."},
        {"Recycle Plus 1 (or 2)","Recycle, then shift 1/2 or 1 spot in flow direction."},
        {"Relay the Diamond","[from parallel ocean waves] swing 1/2. centers cast 3/4, slip, swing while ends circ 2. everyone diamond circulate. centers cast 3/4. [ends in parallel ocean waves]"},
        {"Relay Your Pleasure","From tidal wave. All trade. Center 6 cast 3/4 while outer 2 isolate. Center 2 spread while isolaters press into very center spots while others like a couple up (feels like a courtesy turn). Ends in 1/4 tag."},
        {"Remember the Alamo","From parallel waves.  Outeractives ah so while others split counter rotate.  Ends on O spots/alamo ring. (Careful: the inneractives might be a couple!)"},
        {"Replace the Column","Invert the column 3/4; #1 and #2 counter rotate while #3 moves up to 2/3 recycle with very centers"},
        {"Replace the Column but [Anything]","Invert the column 3/4; #1 and #2 counter rotate while #3 moves up to [anything] with very centers"},
        {"Retreat the Line","As couples quarter out.  (like bend the line, but out instead of in.)"},
        {"Reverse Change-O","From columns: #1 and #4 circ, #2 and #3 cross over circ. (those starting in the middle, cross over)"},
        {"Reverse Flip/Cut the Triangle/Z","Those who are close together {Reverse Flip: trade and slide apart; Reverse Cut: flip away}, while the others [formation] Circulate."},
        {"Reverse the Diamond","Usually from diamonds, but valid whenever center 4 are in a wave.  Centers trade the wave while the ends u-turn back."},
        {"Revert [Atc]","[atc] to the 1/2 tag, cast off 3/4, continue tagging."},
        {"Ride the Tide","Cross trail thru, clover and square thru 2, slide thru"},
        {"Right | Left Anchor [N/4]","Space invader. As a couple, turn [n/4] in [direction], in such a way that the \"center\" dancer stays on the same spot."},
        {"Right | Left Wing","Right Wing = Do the anything call as if you started as a Beau. That is, if you are a Belle, do the anything call as if you had first side-stepped to the left."},
        {"Right and Left By [By [By]]","Right and Left Thru and 1/4 More, then Slither [and slide [and slither]]."},
        {"Right On [N] and [M/4] & Left On","Right/left square thru [n, default 4] but on the last hand cast off [m/4, default 3/4] and roll"},
        {"Right Roll the / Left Roll The","From back-to-back couples. Half of a Drift Around (that is, rip off), creating a diamond.  (beaus 1/2 run while belles 1/2 zoom and take hands.)"},
        {"Rip Saw","From: lines w/ ends looking out. Ends cross fold while centers partner tag & cloverleaf. New centers (the cross folders) pass thru. Ends in eight chain."},
        {"Rip the Line","Centers u-turn back while ends cross fold. (think \"centers pair the line while ends cross pair the line\")"},
        {"Roll 'Em","Here Comes The Judge, but the judge does a zoom instead of circulate."},
        {"Roll Out the Barrel","Right couple: link up (out anchor 1/4, roll, press ahead), circ 2; left couple: tag the line, face in, link up (1/2 circ, cross fire)"},
        {"Roll Out to a Column","Ends right anchor 1/4, roll, press ahead; centers 1/4 right, counter rotate, press ahead"},
        {"Roll the Line/Wave","From any line/wave. U-turn back away from center of line, explode."},
        {"Round & Cross","Round Off and *everyone* Half Sashay.  (That is: From back-to-back lines: Quarter away from the center, and then Tandem U-Turn Back inward, then everyone half sashay.)"},
        {"Round Off","From back-to-back lines. 1/4 away from center, then tandem u-turn back inward (feels like a cloverleaf)"},
        {"Round the Horn","From back-to-back lines. 1/4 away from center. trailers 1/2 stable, tandem u-turn back inward. everyone pass thru."},
        {"Run Away","From line. centers run and roll, while ends face center & right touch 1/2. ends in single 1/4 tag."},
        {"Run Wild","Cross roll to a wave/line, twice (2 parts)"},
        {"Sandwich [Call1] Around [Call2]","Do [call1] interrupt after 1/2 with a [call2].  This has three parts."},
        {"Sashay Thru","Do-sa-do 3/4 and slither."},
        {"Scamper","Typ from 3/4 tag.  Ends divide & touch 1/4 while centers hinge & box circ. (If centers are facing couples, they touch 1/4 & box circ.)  Ends in columns."},
        {"Scatter [Atc] and Dodge","Scattered work stable, scatter [atc]"},
        {"Scatter Concept","If a call normally starts (from waves) with the leads doing a Split Circulate, they do an All 8 Circulate instead."},
        {"Scoot Apart","Trailers step forward, trade, spread while leads box circulate 1-1/2.  cheat 1: \"cross reach out (squeeze instead of flip)\".  cheat 2: follow thru; cross lockit. cross scoot apart = trailers step to opposite hands before trade; criss cross scoot apart = leaders also step to opposite hands after circ"},
        {"Set Back","All trade. lines cross back thru. from waves makes two-faced lines."},
        {"Sets in Motion +1, +2","Add 1/2 more people to outside at end of sets in motion. 1 = peel left to end in center. 2 = peel left/right like first two."},
        {"Sets in Motion Plus 1/2","Add 1/2 more people to outside at end of sets in motion. 1 = peel left to end in center. 2 = peel left/right like first two."},
        {"Settle Back","Reset 1/2, centers cross back while ends o circulate twice"},
        {"Shadow [Formation] [Anything]","From: outsides in tandem, centers in [formation]. Outsides 1/2 zoom and Cast 3/4, while centers [anything]. (ie, outsides cast a shadow but don't spread)"},
        {"Shadow the Column","1 & 3 1/2 zoom, cast off 3/4, spread; 2 cloverleaf. 4 circ 1 1/2, hinge, extend. (like split phantom columns walk and dodge, collapse phantoms, cast a shadow)"},
        {"Shadow to a Diamond","From parallel waves. Ends cast a shadow, centers peel and trail w/ each other. Ends in twin facing diamonds. (checker cheat: 'cast a shadow then centers snake')"},
        {"Shift N","Skip first N parts, do rest of call, then do first N parts"},
        {"Shifty","Shift 1"},
        {"Ship Ahoy","From lines w/ an end facing out: outer actives cycle & wheel, other center shove off in (taking adjacent end)"},
        {"Short & Sweet","From box of 4. leads do their part mini chase, while trailers do their part short cut (beaus phantom touch 1/4, belles partner tag) (alt: move 1 position clockwise around the box & end in a r-h box, but facing side if you were facing head & vice-versa)"},
        {"Short Cut","From facing couples: beaus (phantom) touch 1/4 while belles partner tag."},
        {"Short Cycle","From wave or inverted line: centers u-turn back (toward nearest end), couples hinge."},
        {"Short Trip","[usually from waves] end looking out and adjacent center (outeractives) squeeze; while others circulate"},
        {"Shuffle & Wheel","Like Shuffle the Deck, but the belle-side couple does a Wheel and Deal to face the beau-side Couple.  From 1-faced line, ends in couples facing."},
        {"Shuffle the Deck","As couples single shuffle.  That is, as couples (belle step in front like in dixie style to a wave, dixie chain, vert tag (from facing couples), etc.)"},
        {"Shuttle [Dir | Call]","From 8 chain. All pass thru; centers slide through while ends [call] or 1/4 [dir]."},
        {"Siamese Breakdown","From 1x2: laterally adjacent people (couple or miniwave) Single Wheel, while vertically adjacent people (tandem, facing, back-to-back) Single Turn to a Line (leaders go right, trailers go left)."},
        {"Single Concept","Every dancer becomes a couple or tandem, as necessary. Think center dancer of 3x3: \"Be the cheese.\""},
        {"Single File Concept","Think of doing the call up to the point where someone crosses the center line of the 2x2.  Now start the call from there."},
        {"Single Hinge & Trade","All hinge, centers trade, all roll. (This is the start of the centers part of sets in motion.)"},
        {"Single Scoot and Trade","Scoot back, ends quarter to handhold while centers hinge; everyone lockit"},
        {"Skew, Skewsome, Skew 1/4 Skewsome Concepts","Skew is like As Couples or Tandem, but the people being paired are neither beside each other nor in tandem. They are diagonal from each other in a 2x2 box. Skewsome is the Twosome version of this."},
        {"Slim Down","Centers become ends, vice versa, no turning. 2x4 -> 4x2"},
        {"Snag [Anything]","Snag == Snag the centers.  That is, centers do 1/2 [anything] while ends [anything]."},
        {"Snag the [Anyone] [Anything]","[anyone] do 1/2 [anything], while the others [anything]."},
        {"Snake","From miniwave, quarter in and step to wave of opposite handedness"},
        {"Snap","Partner tag"},
        {"Snap the Diamond","Diamond partner tag (centers/points working disconnected; to spots); outsides partner tag while centers right roll to a wave."},
        {"Snap the Tag [N/4]","Right shoulder partner tag. ends u-turn back. extend n times. [ambiguity on reflect, since 1st part is another tagger]"},
        {"Soft [Anything]","Centers hinge and flip away while the others 1/4 in, step ahead, and [anything]"},
        {"Soft Touch","[from line or diamond] centers hinge and flip away while the others 1/4 in, step ahead, and touch"},
        {"Spin a Wheel","Couples hinge, triple trade, couples hinge."},
        {"Spin Back","All trade/touch 1/2; centers cast 3/4 while ends u-turn back"},
        {"Spin Chain & Circulate In","Trade/touch 1/2.  Then 3/4 chain and circulate in (ends circ & cross over circ, while centers cast 3/4, very centers trade, cast 3/4, spread.)"},
        {"Spin Chain and Circulate the Gears","Spin Chain the Gears, but everytime the ends u-turn back they circulate afterwards."},
        {"Spin Chain the Star","2-3-2-3 quarter the deucey"},
        {"Spin Tag the Deucey","Spin chain thru; new ends tag thru, 1/4 right, circ 1"},
        {"Splash [Direction/Anything]","Outeractives explode the wave/line. inneractives vertical tag & [face dir]/[anything]"},
        {"Split Cast [N/4]","Usually from 'heads touch'. Centers cast 1/2 (maybe pushy) while ends hinge & trade.  With a fraction, after the ends hinge everyone casts n/4."},
        {"Split the Difference","Split circulate the difference"},
        {"Split Trade the Difference","Split trade circulate the difference"},
        {"Split Turn & Q","Those facing turn thru, face the others; all left turn thru"},
        {"Square Out","From 8 chain: centers square thru 4 while ends 8-chain 2 and square thru 2."},
        {"Square the Barge [N/4]","Square thru N/4.  Trade by.  (N defaults to 4) (Barge thru is square the barge 2/4)"},
        {"Square the Barge [N/4] the Action","Square thru N/4.  The action.  (N defaults to 4)"},
        {"Square the Bases Plus 2","Square the Bases, but the Split Square Thru 2 is changed to a Split Square Thru 4."},
        {"Square Turn Thru [N]","Square thru [n], but do a natural turn thru on the last hand (instead of natural pull by)"},
        {"Stack the Wheel","As couples hinge, individually roll"},
        {"Standard Concept","Boys are Standard in Split Phantom Lines Counter Rotate 1/4 means divide the formation such that the boys are in split phantom lines -- if you are t-boned, you might end up doing the call in split phantom columns."},
        {"Star to a Wave","1/2 reverse swap around; counter rotate the diamond 1/2; flip the diamond. (equivalent to tag the star 1/2 & hinge)"},
        {"Step Lively","Detour, slim down, circulate"},
        {"Straight","The end looking in (who must be in line-like orientation) does a Press In (\"Cross Over Circulate\"), while the others do the call normally."},
        {"Straight Away","From 1/4 tag/line. end of center line extends to outside & release [recycle]. very center flips out. other outside press ahead. ends in 1/4 tag/line."},
        {"Straight Connect","End looking in crossover circ while others (centers hinge and extend while points fold or cross fold) (\"straight connect the diamond\")"},
        {"Straightfire","From 2-faced lines. ends looking in cross over circulate, while others crossfire. (\"straight crossfire\")"},
        {"Strike Out","Centers hinge; all collapse (ends detour, centers step and fold). [from rh waves becomes magic column]"},
        {"Stroll & Cycle","From 1/4 line. very centers trade, end of center line extend to outside & release [recycle] & plus 2 becoming trailing couple. other outside press out to very center & both step ahead becoming lead couple. ends in two-faced lines."},
        {"Stroll Down the Lane","[from facing lines] end on the left press out to meet other end, they recycle and veer left; centers hammerlane and step forward. [ends in parallel 2-faced lines]"},
        {"Swing About","Swing, Slip, Explode. (That is, there's an extra 'slip' added in the middle.)"},
        {"Swing an Anchor","Trade; an anchor (8-6-4-2)"},
        {"Swing Chain [Foo]","Spin chain [foo] except replace all 3/4 turns w/ 1/4 turns."},
        {"Swing Chain the Line","Spin Chain the Line, but change all 3/4 turns to 1/4 turns.  That is: arm turn 1/2, centers cast 1/4 and spread while very centers trade, then very centers and ends slide together and cast 1/4."},
        {"Swing Concept","Make all 3/4 arm turns in the call (including star turns) into 1/4 turns."},
        {"Swing to a Column","From general qtr tag (usually rh 3/4 tag). center line trade & roll then walk forward to be #1 and #2 of column. ends divide, touch, flip the line 1/2 to become #3 and #4. all passes are right shoulder."},
        {"Switcheroo","Switch to a diamond, eroo.  (switch to a diamond, ends circ while centers cast 3/4)"},
        {"Tag Circulate","Typically from 2-faced lines. Trailers circulate. Leads tag the line face right. (This is a circulate variant; careful with \"tag percolate\")"},
        {"Tag the Star","1/2 reverse swap around, counter rotate the diamond N/4 (default 2), drop in (gives 1/2 tag)"},
        {"Tap the [Anyone]","From facing couples. Pass thru, [anyone] u-turn back, box counter rotate, roll. 4 parts, evaluate [anyone] just before u-turn back."},
        {"The Action","Ends linear action, centers 1/2 reverse swap around, turn star 1/4, like a chain reaction"},
        {"The Difference","Cast off 3/4, slip, cast off 3/4"},
        {"The Plank","Centers walk and dodge, ends leads run"},
        {"Tickle","Hinge; split counter rotate [from waves, equiv to ah so]"},
        {"Touch & Go [M/4] by [N/4 or Anything]","From columns: all 1/2 circ. outer two isolate & circ, others cast [m/4]. 4 who meet cast [n/4] or [anything], other 2 isolate. [stimulate the column is circ & touch and go 1/4 by 3/4]"},
        {"Touch of Class","[from waves] leads switch and circulate while trailers extend, recycle, plus 2 [slide 1 matrix spot in sweep dir] [ends in parallel 2-faced lines]"},
        {"Touch Tone [M/4] by [N/4]","From waves. Extend, ends cast back and touch (if original waves were rh) or left touch (if original waves were lh).  Centers cast m/4, ends cast n/4.  Can use calls instead of fractions."},
        {"Trace [Call1] by [Call2]","Trace is done from a 1/4-tag-like or diamond-like setup. Each end of the center line, and his adjacent person, do [call1] with the outside people that he faces, in a distorted 2x2 box. Those outsides work with the other two people in the center line for [call2], which is also done in a distorted 2x2 box."},
        {"Trail Chain Thru","From trade by or 3/4 tag. centers swing slip as outsides CROSS cast back and touch 1/2. fan the top. usually ends in parallel waves."},
        {"Trail the Deal","Cross Loop and Tag Zero."},
        {"Trans [Anything]","Transfer and cast 3/4; [anything]"},
        {"Transaction","Trans chain reaction"},
        {"Trim the Web","From I or t-bone 2x4: centers touch (if necessary) and trade. outer 6 then make a 3-person star and turn it 2/3.  ends face in.  Star will be of consistent handedness: everyone puts the same hand in that center has."},
        {"Triple Cast","Typ. from tidal wave: center 6 cast 3/4, while outer 2 u-turn back away from the center & isolate. Center 2 then \"move up\".  From tidal wave ends in parallel waves; from p2p diamonds ends in twin diamonds."},
        {"Triple Turn","Turn to a line, turn and deal, turn to a line."},
        {"Triple Wheel","Wheel to a Line, Wheel and Deal, and Wheel to a Line."},
        {"Trixie","From 2x2: leads quarter in, trailers quarter out. \"Throw your inside hand in.\" The hand you're holding with your couple-partner becomes the hand you hold with your tandem-partner (who becomes your new couple-partner)."},
        {"Trixie Spin","Trixie, cast 3/4, centers cross run. (3 parts).  Trixie is \"leads 1/4 in, trailers 1/4 out.\""},
        {"Tunnel [Anything]","From general columns: centers partner tag, step ahead, and trade; while ends vertical 1/2 tag into center, [anything].  (If [anything] is a direction, quarter [direction] relative to center, and call ends in general columns.)"},
        {"Tunnel Thru","From general columns: centers partner tag, step ahead, and trade; while ends vertical tag to become centers."},
        {"Turn & Left Thru","Turn thru and courtesy turn. (for example, from rh wave to couples facing)"},
        {"Turn & Q","Turn thru, quarter in, left turn thru"},
        {"Turn & Weave (Box & Column, 1/4 Tag)","Touch (if necessary, until exist miniwave), (those in miniwave) trade, extend (if necessary until everyone in miniwaves), weave."},
        {"Turn Away","Belles peel off and circulate while the beaus trail off [typically from compl DPT, to parallel 2-faced lines]"},
        {"Turn By","Single eight chain 1 or trade by (as appropriate), outsides always turn to the right."},
        {"Turn On","Split counter rotate; extend (2 parts)"},
        {"Turntable","Centers 1/4 right and once removed circulate twice; ends move in and single rotate 1/2"},
        {"Twisted","Two dancers who would exchange places (typically on a pull by) rotate 1/4 halfway through exchange. examples: twisted pass in, twisted half sashay, twisted zoom, finally twisted line to line"},
        {"Veer & Turn [M/4] X [N/4]","Veer (in natural direction). Centers cast off [m/4] while ends turn [n/4], starting with turn in (ie, ends qtr in & roll & roll etc until pass [n] walls)"},
        {"Vertical Turn and Deal","[from 2x2] vertical 1/2 tag then \"roll as if you could\".  Note that often not everyone can roll, eg from a miniwave box or facing couples. from couples facing out gives lh box."},
        {"Walk Out to a Column","Those looking out once removed single wheel & step forward to be #2 and #3; trailers all-8 circ and step & fold (trailing center walk forward to be #1; trailing end walk forward and fold to be #4)"},
        {"Walk the (Cross) Clover","Often from trade by: outsides (cross) cloverleaf; while centers (touch 1/4; walk & dodge). If centers are in wave, hinge & walk and dodge.  If from parallel waves, extend first, then do the call."},
        {"Walk the Plank","Circulate the plank"},
        {"Wheel to a Diamond","Leads wheel around, belles 1/2 cross (taking right hands) while beaus quarter left"},
        {"Wheel to a Line","As couples Single Turn to a Line. That is, any lead couple goes right and any trailing couple goes left."},
        {"Wheel to an Hourglass","Wheel to a diamond, very centers snake"},
        {"Wipe Out","[from waves or 2-faced lines] ends do their part swing & slip while centers scoot back and spread [ends in waves or 2-faced lines]"},
        {"With Finesse","Ends cast 3/4 and spread like a checkpoint. centers zing and step to oppposite hands. (centers roll back from col of 6)"},
        {"You All","Centers hinge while ends u-turn back. (From tidal wave, centers of each side.)"},
        {"Yoyo","Turn first arm turn 1/2 (or equivalent trade) into arm turn 3/4"},
        {"Z Cols/Lines/Waves Formation","This is just a special case of Distorted Columns, Lines, or Waves. Work to spots.  (From parallel waves, think of the setup after centers press ahead.)"},
        {"Zip the Top","Lockit, centers u-turn back (toward each other)."},
};
